/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SomeIndexRouteImport } from './routes/some/index'
import { Route as OneIndexRouteImport } from './routes/one/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SomeIndexRoute = SomeIndexRouteImport.update({
  id: '/some/',
  path: '/some/',
  getParentRoute: () => rootRouteImport,
} as any)
const OneIndexRoute = OneIndexRouteImport.update({
  id: '/one/',
  path: '/one/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/one': typeof OneIndexRoute
  '/some': typeof SomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/one': typeof OneIndexRoute
  '/some': typeof SomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/one/': typeof OneIndexRoute
  '/some/': typeof SomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/one' | '/some'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/one' | '/some'
  id: '__root__' | '/' | '/one/' | '/some/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OneIndexRoute: typeof OneIndexRoute
  SomeIndexRoute: typeof SomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/some/': {
      id: '/some/'
      path: '/some'
      fullPath: '/some'
      preLoaderRoute: typeof SomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one/': {
      id: '/one/'
      path: '/one'
      fullPath: '/one'
      preLoaderRoute: typeof OneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OneIndexRoute: OneIndexRoute,
  SomeIndexRoute: SomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
